---
- name: Установка необходимых пакетов
  apt:
    name:
      - acl
      - python3-psycopg2
      - postgresql
      - postgresql-contrib
    state: present
  become: yes

- name: Создать каталог данных для PostgreSQL на внешнем диске
  file:
    path: "{{ postgresql_data_directory }}"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'
  become: yes

- name: Обновить конфигурацию PostgreSQL для использования нового каталога данных
  lineinfile:
    path: "/etc/postgresql/16/main/postgresql.conf"
    regexp: '^data_directory ='
    line: "data_directory = '{{ postgresql_data_directory }}'"
  notify: Перезапустить PostgreSQL
  become: yes

- name: Инициализация кластера базы данных в новом каталоге
  command: "/usr/lib/postgresql/16/bin/initdb -D {{ postgresql_data_directory }}"
  args:
    creates: "{{ postgresql_data_directory }}/PG_VERSION"
  become: yes
  become_user: postgres

- name: Убедиться, что PostgreSQL запущен и включен
  service:
    name: postgresql
    state: started
    enabled: true

- name: Создание базы данных
  become_user: postgres
  postgresql_db:
    name: "{{ postgresql_database }}"
    encoding: "{{ postgresql_encoding }}"
    lc_collate: "{{ postgresql_locale }}"
    lc_ctype: "{{ postgresql_locale }}"
    state: present

- name: Создание пользователя базы данных
  become_user: postgres
  postgresql_user:
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_password }}"
    state: present

- name: Назначение привилегий пользователю на базу данных
  become_user: postgres
  postgresql_privs:
    db: "{{ postgresql_database }}"
    type: database
    privs: "ALL"
    roles: "{{ postgresql_user }}"
    state: present

