---
- name: Проверить, установлен ли ufw
  apt:
    name: ufw
    state: present
  register: ufw_installed

- name: Разрешить необходимые порты через ufw
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_ports }}"

- name: Включить и перезапустить ufw
  ufw:
    state: enabled
