---
- name: Проверить, установлен ли fail2ban
  apt:
    name: fail2ban
    state: present

- name: Проверить наличие файла /etc/fail2ban/jail.local
  stat:
    path: /etc/fail2ban/jail.local
  register: jail_local_file

- name: Скопировать конфигурацию fail2ban, если jail.local не существует
  copy:
    src: /etc/fail2ban/jail.conf
    dest: /etc/fail2ban/jail.local
    remote_src: yes
  when: not jail_local_file.stat.exists
  notify: Перезапустить fail2ban

- name: Убедиться, что fail2ban запущен и включён
  service:
    name: fail2ban
    state: started
    enabled: true


